[project]
name = "retark"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "peft>=0.17.0",
    "transformers>=4.55.2",
    "trl>=0.21.0",
]
